<?php
    $treino = $this->treino; 
?>
<div class="col-lg-12 col-sm-12 col-xs-12">
    <div class="well bg-darkcarbon  ">
       
        <h1 class="block"> <i class=" fa fa-list-alt "></i><b>    TREINO :</b> <?php echo strtoupper( $treino[0]['ST_IDENTIFICADOR_TRE'] )?></h1>
        <p>
            <b>OBJETIVO :</b> <?php echo strtoupper(utf8_decode( $treino[0]['ST_NOME_OBJ']) )?>
        </p>
    </div>
</div>